<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AppStatus extends \Entities\AppStatus implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setDate($value)
    {
        $this->__load();
        return parent::setDate($value);
    }

    public function prePersistSetDate()
    {
        $this->__load();
        return parent::prePersistSetDate();
    }

    public function getUpdatedServers()
    {
        $this->__load();
        return parent::getUpdatedServers();
    }

    public function setUpdatedServers($value)
    {
        $this->__load();
        return parent::setUpdatedServers($value);
    }

    public function getNewServers()
    {
        $this->__load();
        return parent::getNewServers();
    }

    public function setNewServers($value)
    {
        $this->__load();
        return parent::setNewServers($value);
    }

    public function getUpdatedPlayers()
    {
        $this->__load();
        return parent::getUpdatedPlayers();
    }

    public function setUpdatedPlayers($value)
    {
        $this->__load();
        return parent::setUpdatedPlayers($value);
    }

    public function getNewPlayers()
    {
        $this->__load();
        return parent::getNewPlayers();
    }

    public function setNewPlayers($value)
    {
        $this->__load();
        return parent::setNewPlayers($value);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'date', 'updatedServers', 'newServers', 'updatedPlayers', 'newPlayers');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}